name: Configure Exercise

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_1_FILE: ".github/steps/1-step.md"

jobs:
  disable_workflows:
    name: Disable exercise workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Disable all exercise workflows
        run: |
          # Find all workflow files that start with a number (0-9)
          workflows=$(git ls-files | grep -E '^\.github/workflows/[0-9].*\.(yml|yaml)$')
          for workflow in $workflows; do
            workflow_name="$(basename "$workflow")"
            echo "Disabling workflow: $workflow_name"
            gh workflow disable "$workflow_name" || true
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  update_readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build welcome message from template
        id: build-new-readme
        uses: skills/action-text-variables@v3
        with:
          template-file: .github/markdown-templates/readme/configure-exercise.md
          template-vars: |
            title: "Introduction to Terraform"
            login: ${{ github.actor }}

      - name: Overwrite README
        env:
          README_TEXT: ${{ steps.build-new-readme.outputs.updated-text }}
        run: echo "$README_TEXT" > README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Update README with exercise configuration link"
          default_author: github_actions

      - name: Enable next workflow
        run: gh workflow enable "Step 0"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
